# Generated by Django 5.2.5 on 2025-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_senha', models.CharField(max_length=128)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
